version: '3'

services:

  postgres:
    image: postgres
    restart: always
    networks:
      - coffee-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Postgres2022!
    volumes:
      - ./script-postgresql.sql:/docker-entrypoint-initdb.d/script-postgresql.sql

networks:
  coffee-network:
    driver: bridge